name: dtool-lookup-framework-test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    uses: livMatS/dtool-framework-workflows/.github/workflows/dtool-lookup-api-vs-dserver-container-composition-cross-test.yml@master
